name: Tests

on:
  push:
    paths-ignore:
      - "**/*.md"
      - "/.gitignore"
    branches:
      - main

permissions:
  contents: write
  actions: write

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        java-version: ["8", "11", "17", "21"]
        os: [ubuntu, macOS]
        exclude:
          - java-version: "8"
            os: macOS

    runs-on: ${{ matrix.os }}-latest
    name: test-${{ matrix.os }}-temurin-${{ matrix.java-version }}

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - run: |
          # Note: the following account information will not work on GHES
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - uses: taiki-e/install-action@just

      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java-version }}

      - name: "Restore Cache"
        uses: "actions/cache@v4"
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: "${{ runner.os }}-deps-${{ hashFiles('deps.edn','bb.edn') }}"

      - name: Setup Babashka
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          bb: "latest"
          cli: "latest"

      - name: Tools Versions
        run: |
          java -version
          bb --version

      - name: Run big-config tests
        env:
          ZELLIJ_SESSION_NAME: test-${{ matrix.os }}-temurin-${{ matrix.java-version }}
        run: |
          just test

      - name: Run big-config tests
        run: |
          just tofu opts alpha dev
